/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SliderSpinner.java
 *
 * Created on 08/04/2010, 20:53:46
 */
package jxSpinner;

import javax.swing.JPanel;
import javax.swing.border.TitledBorder;

/**
 *
 * @author rafael
 */
public class SliderSpinner extends JPanel {

    public static enum PresentationOrder {

        SLIDER_FIRST, SPINNER_FIRST
    }

    public static enum Orientation {

        HORIZONTAL, VERTICAL
    }


    public static final String PROP_TITULO = "titulo";
    public static final String PROP_PRESENTATION = "presentationOrder";
    public static final String PROP_ORIENTATION = "orientation";

    /** Creates new form BeanForm */
    public SliderSpinner() {
        this.presentationOrder = PresentationOrder.SLIDER_FIRST;
        initComponents();
    }

    private TitledBorder getTitledBorder() {
        return (TitledBorder) this.getBorder();
    }

    private void changeLayout() {

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        slider = new javax.swing.JSlider();
        pnlSlider = new javax.swing.JPanel();
        spinner = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new java.awt.BorderLayout(5, 5));

        slider.setPaintLabels(true);
        slider.setPaintTicks(true);
        slider.setMinimumSize(new java.awt.Dimension(200, 31));
        add(slider, java.awt.BorderLayout.CENTER);

        pnlSlider.add(spinner);

        add(pnlSlider, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlSlider;
    private javax.swing.JSlider slider;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
    private PresentationOrder presentationOrder;
    private Orientation orientation;

    public String getTitulo() {
        return this.getTitledBorder().getTitle();
    }

    public void setTitulo(String titulo) {
        String oldValue = this.getTitledBorder().getTitle();
        this.getTitledBorder().setTitle(titulo);
        super.firePropertyChange(PROP_TITULO, oldValue, titulo);
    }

    public PresentationOrder getPresentationOrder() {
        return presentationOrder;
    }

    public void setPresentationOrder(PresentationOrder presentationOrder) {
        if (presentationOrder != this.presentationOrder) {
            Object oldValue = this.presentationOrder;
            this.presentationOrder = presentationOrder;
            super.firePropertyChange(PROP_PRESENTATION, oldValue, this.presentationOrder);
        }
    }

    public Orientation getOrientation() {
        return orientation;
    }

    public void setOrientation(Orientation orientation) {
        if (this.orientation != orientation) {
            Object oldValue = this.orientation;
            this.orientation = orientation;
            super.firePropertyChange(PROP_ORIENTATION, oldValue, this.orientation);
        }
    }
}
