package testeswing;

/**
 * Molde das aplicaçõe de gráfico.
 * 
 * @author rafael
 */
public class GraphFrame extends javax.swing.JFrame {

    /** Creates new form TestGraph5 */
    public GraphFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControle = new javax.swing.JPanel();
        pnlEquacao = new javax.swing.JPanel();
        lblEquacao = new org.jdesktop.swingx.JXLabel();
        graph = new org.jdesktop.swingx.JXGraph();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pnlControleLayout = new javax.swing.GroupLayout(pnlControle);
        pnlControle.setLayout(pnlControleLayout);
        pnlControleLayout.setHorizontalGroup(
            pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        pnlControleLayout.setVerticalGroup(
            pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );

        getContentPane().add(pnlControle, java.awt.BorderLayout.PAGE_END);

        lblEquacao.setText("XXX");
        pnlEquacao.add(lblEquacao);

        getContentPane().add(pnlEquacao, java.awt.BorderLayout.PAGE_START);

        graph.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout graphLayout = new javax.swing.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        getContentPane().add(graph, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    *
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphFrame().setVisible(true);
            }
        });
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXGraph graph;
    private org.jdesktop.swingx.JXLabel lblEquacao;
    private javax.swing.JPanel pnlControle;
    private javax.swing.JPanel pnlEquacao;
    // End of variables declaration//GEN-END:variables

}
