/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteGraph4.java
 *
 * Created on 22/03/2010, 22:21:18
 */

package testeswing;

/**
 *
 * @author rafael
 */
public class TesteGraph4 extends javax.swing.JFrame {

    /** Creates new form TesteGraph4 */
    public TesteGraph4() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph = new testeswing.MyJXGraph();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TesteGraph 4 - Exibir Retas");
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        graph.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        graph.setMajorX(1.0);
        graph.setMajorY(1.0);
        graph.setView(new java.awt.geom.Rectangle2D.Double(0.0, -0.5, 5.0, 5.5));

        javax.swing.GroupLayout graphLayout = new javax.swing.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        getContentPane().add(graph, java.awt.BorderLayout.CENTER);
        graph.addPontos(1.0, 2.0, 3.0, 1.0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteGraph4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private testeswing.MyJXGraph graph;
    // End of variables declaration//GEN-END:variables

}
