/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteTabela.java
 *
 * Created on 11/03/2010, 22:14:50
 */
package testeswing;

import testeswing.tabela.TableNumber;

/**
 *
 * @author rafael
 */
public class TesteTabela extends javax.swing.JFrame {

    /** Creates new form TesteTabela */
    public TesteTabela() {
        initComponents();
        this.criarNovaTabela((Integer)this.spnLados.getValue());
        this.spnLados.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlControle = new javax.swing.JPanel();
        lblLados = new javax.swing.JLabel();
        spnLados = new javax.swing.JSpinner();
        scpNumeros = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(200, 400));

        lblLados.setLabelFor(spnLados);
        lblLados.setText("Lados: ");

        spnLados.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spnLados.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnLadosStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlControleLayout = new javax.swing.GroupLayout(pnlControle);
        pnlControle.setLayout(pnlControleLayout);
        pnlControleLayout.setHorizontalGroup(
            pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lblLados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnLados, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        pnlControleLayout.setVerticalGroup(
            pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControleLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLados)
                    .addComponent(spnLados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(pnlControle, java.awt.BorderLayout.PAGE_END);

        scpNumeros.setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(scpNumeros, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnLadosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnLadosStateChanged
        this.criarNovaTabela((Integer) this.spnLados.getValue());
    }//GEN-LAST:event_spnLadosStateChanged

    private void criarNovaTabela(int size) {
        this.scpNumeros.setViewportView(new TableNumber(size));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TesteTabela().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLados;
    private javax.swing.JPanel pnlControle;
    private javax.swing.JScrollPane scpNumeros;
    private javax.swing.JSpinner spnLados;
    // End of variables declaration//GEN-END:variables

}
