/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteGraph2.java
 *
 * Created on 18/03/2010, 22:12:17
 */
package testeswing;

import java.awt.Color;
import java.util.Arrays;
import org.jdesktop.swingx.JXGraph;

/**
 *
 * @author rafael
 */
public class TesteGraph2 extends javax.swing.JFrame {

    /** Creates new form TesteGraph2 */
    public TesteGraph2() {
        initComponents();
        changeK();
        System.out.println(Arrays.toString(this.spnK.getRegisteredKeyStrokes()));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph = new org.jdesktop.swingx.JXGraph();
        pnlControle = new org.jdesktop.swingx.JXPanel();
        lblK = new org.jdesktop.swingx.JXLabel();
        spnK = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        graph.setMajorX(0.1);
        graph.setMajorY(0.1);
        graph.setMinorCountX(2);
        graph.setMinorCountY(2);
        graph.setView(new java.awt.geom.Rectangle2D.Double(0.0, -0.1, 1.0, 1.1));

        javax.swing.GroupLayout graphLayout = new javax.swing.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        getContentPane().add(graph, java.awt.BorderLayout.CENTER);
        graph.addPlots(Color.RED, this.parabolaPlot);
        graph.addPlots(Color.BLUE, new LinePlot());

        lblK.setLabelFor(spnK);
        lblK.setText("k = ");

        spnK.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 4.0d, 0.01d));
        spnK.setEditor(new javax.swing.JSpinner.NumberEditor(spnK, "0.00"));
        spnK.setValue(1.0);
        spnK.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnKStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlControleLayout = new javax.swing.GroupLayout(pnlControle);
        pnlControle.setLayout(pnlControleLayout);
        pnlControleLayout.setHorizontalGroup(
            pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControleLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(lblK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnK, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        pnlControleLayout.setVerticalGroup(
            pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControleLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(pnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        spinnerListener.bindSpinner(spnK);

        getContentPane().add(pnlControle, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnKStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnKStateChanged
        this.changeK();
    }//GEN-LAST:event_spnKStateChanged

    private void changeK() {
        this.parabolaPlot.setK((Double) this.spnK.getValue());
        this.graph.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TesteGraph2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXGraph graph;
    private org.jdesktop.swingx.JXLabel lblK;
    private org.jdesktop.swingx.JXPanel pnlControle;
    private javax.swing.JSpinner spnK;
    // End of variables declaration//GEN-END:variables
    private ParabolaPlot parabolaPlot = new ParabolaPlot();
    private ExpandedSpinnerListener spinnerListener = new ExpandedSpinnerListener();
}

class ParabolaPlot extends JXGraph.Plot {

    private double k;

    public void setK(double k) {
        double oldK = k;
        this.k = k;
        super.firePropertyChange("k", oldK, this.k);
    }

    @Override
    public double compute(double x) {
        return k * x * (1 - x);
    }
}

class LinePlot extends JXGraph.Plot {

    @Override
    public double compute(double x) {
        return x;
    }

}