/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteGraph.java
 *
 * Created on 18/03/2010, 21:01:07
 */

package testeswing;

import java.awt.Color;
import org.jdesktop.swingx.JXGraph;

/**
 *
 * @author rafael
 */
public class TesteGraph extends javax.swing.JFrame {

    /** Creates new form TesteGraph */
    public TesteGraph() {
        initComponents();

        this.senoPlot.setAmplitude((Double) this.spnAmplitude.getValue());
        this.senoPlot.setFrequencia((Double) this.spnFrequencia.getValue());
        this.senoPlot.setValorInicial((Double) this.spnValorInicial.getValue());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph = new org.jdesktop.swingx.JXGraph();
        pnlControles = new org.jdesktop.swingx.JXPanel();
        lblAmplitude = new javax.swing.JLabel();
        spnAmplitude = new javax.swing.JSpinner();
        lblFrequencia = new javax.swing.JLabel();
        spnFrequencia = new javax.swing.JSpinner();
        lblValorInicial = new javax.swing.JLabel();
        spnValorInicial = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teste de Gráfico");
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        graph.setMajorX(0.5);
        graph.setMajorY(0.5);
        graph.setView(new java.awt.geom.Rectangle2D.Double(-1.5, -1.5, 3.0, 3.0));
        this.graph.addPlots(Color.BLUE, this.senoPlot);

        javax.swing.GroupLayout graphLayout = new javax.swing.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        getContentPane().add(graph, java.awt.BorderLayout.CENTER);

        lblAmplitude.setText("Amplitude");

        spnAmplitude.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 2.0d, 0.1d));
        spnAmplitude.setEditor(new javax.swing.JSpinner.NumberEditor(spnAmplitude, "0.0 "));
        spnAmplitude.setValue(1.0);
        spnAmplitude.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnAmplitudeStateChanged(evt);
            }
        });

        lblFrequencia.setText("Frequência");

        spnFrequencia.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 2.0d, 0.010000000000000009d));
        spnFrequencia.setEditor(new javax.swing.JSpinner.NumberEditor(spnFrequencia, "0.00"));
        spnFrequencia.setPreferredSize(new java.awt.Dimension(31, 20));
        spnFrequencia.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnFrequenciaStateChanged(evt);
            }
        });

        lblValorInicial.setText("Valor Inicial");

        spnValorInicial.setModel(new javax.swing.SpinnerNumberModel(0.0d, -1.0d, 1.0d, 0.05d));
        spnValorInicial.setEditor(new javax.swing.JSpinner.NumberEditor(spnValorInicial, "0.00"));
        spnValorInicial.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnValorInicialStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlControlesLayout = new javax.swing.GroupLayout(pnlControles);
        pnlControles.setLayout(pnlControlesLayout);
        pnlControlesLayout.setHorizontalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAmplitude)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnAmplitude, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFrequencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValorInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        pnlControlesLayout.setVerticalGroup(
            pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlControlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmplitude)
                    .addComponent(spnAmplitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFrequencia)
                    .addComponent(spnFrequencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorInicial)
                    .addComponent(spnValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        ExpandedSpinnerListener.bindSpinner(spnAmplitude);
        ExpandedSpinnerListener.bindSpinner(spnFrequencia);
        ExpandedSpinnerListener.bindSpinner(spnValorInicial);

        getContentPane().add(pnlControles, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spnAmplitudeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAmplitudeStateChanged
        this.senoPlot.setAmplitude((Double) this.spnAmplitude.getValue());
    }//GEN-LAST:event_spnAmplitudeStateChanged

    private void spnFrequenciaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnFrequenciaStateChanged
        this.senoPlot.setFrequencia((Double) this.spnFrequencia.getValue());
    }//GEN-LAST:event_spnFrequenciaStateChanged

    private void spnValorInicialStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnValorInicialStateChanged
        this.senoPlot.setValorInicial((Double) this.spnValorInicial.getValue());
    }//GEN-LAST:event_spnValorInicialStateChanged

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesteGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXGraph graph;
    private javax.swing.JLabel lblAmplitude;
    private javax.swing.JLabel lblFrequencia;
    private javax.swing.JLabel lblValorInicial;
    private org.jdesktop.swingx.JXPanel pnlControles;
    private javax.swing.JSpinner spnAmplitude;
    private javax.swing.JSpinner spnFrequencia;
    private javax.swing.JSpinner spnValorInicial;
    // End of variables declaration//GEN-END:variables
    private SenoPlot senoPlot = new SenoPlot();
}


class SenoPlot extends JXGraph.Plot {

    private double amplitude = 1;

    private double frequencia = 1;

    private double valorInicial = 0;

    private static double PI_DOIS = Math.PI / 2;

    @Override
    public double compute(double value) {
        return this.valorInicial + amplitude * Math.sin(PI_DOIS * value / this.frequencia);
    }

    public void setAmplitude(double amplitude) {
        double oldValue = this.amplitude;
        this.amplitude = amplitude;
        super.firePropertyChange("amplitude", oldValue, this.amplitude);
    }

    public void setFrequencia(double frequencia) {
        double oldValue = this.frequencia;
        this.frequencia = frequencia;
        super.firePropertyChange("frequencia", oldValue, this.frequencia);
    }

    public void setValorInicial(double valorInicial) {
        double oldValue = this.valorInicial;
        this.valorInicial = valorInicial;
        super.firePropertyChange("valor inicial", oldValue, this.valorInicial);
    }



}