/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TesteGraph2.java
 *
 * Created on 18/03/2010, 22:12:17
 */
package testeswing;

import java.awt.Color;
import java.util.Arrays;
import org.jdesktop.swingx.JXGraph;

/**
 *
 * @author rafael
 */
public class TesteGraph2 extends javax.swing.JFrame {

    /** Creates new form TesteGraph2 */
    public TesteGraph2() {
        initComponents();
        changeK();
        System.out.println(Arrays.toString(this.sliderSpinnerK.getRegisteredKeyStrokes()));
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graph = new org.jdesktop.swingx.JXGraph();
        pnlControle = new org.jdesktop.swingx.JXPanel();
        sliderSpinnerK = new jxSpinner.SliderSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        graph.setMajorX(0.1);
        graph.setMajorY(0.1);
        graph.setMinorCountX(2);
        graph.setMinorCountY(2);
        graph.setView(new java.awt.geom.Rectangle2D.Double(0.0, -0.1, 1.0, 1.1));

        javax.swing.GroupLayout graphLayout = new javax.swing.GroupLayout(graph);
        graph.setLayout(graphLayout);
        graphLayout.setHorizontalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );
        graphLayout.setVerticalGroup(
            graphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        getContentPane().add(graph, java.awt.BorderLayout.CENTER);
        graph.addPlots(Color.RED, this.parabolaPlot);
        graph.addPlots(Color.BLUE, new LinePlot());

        pnlControle.setLayout(new java.awt.BorderLayout());

        sliderSpinnerK.setExtendedStep(0.5);
        sliderSpinnerK.setMaximum(4.00);
        sliderSpinnerK.setMinimum(0.0);
        sliderSpinnerK.setOrientation(jxSpinner.SliderSpinner.Orientation.VERTICAL);
        sliderSpinnerK.setPattern("0.00");
        sliderSpinnerK.setStep(0.01);
        sliderSpinnerK.setTitulo("K");
        sliderSpinnerK.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sliderSpinnerKPropertyChange(evt);
            }
        });
        pnlControle.add(sliderSpinnerK, java.awt.BorderLayout.EAST);

        getContentPane().add(pnlControle, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderSpinnerKPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sliderSpinnerKPropertyChange
        this.changeK();
        System.out.println(this.sliderSpinnerK.getValue());
    }//GEN-LAST:event_sliderSpinnerKPropertyChange

    private void changeK() {
        this.parabolaPlot.setK((Double) this.sliderSpinnerK.getValue());
        this.graph.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TesteGraph2().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXGraph graph;
    private org.jdesktop.swingx.JXPanel pnlControle;
    private jxSpinner.SliderSpinner sliderSpinnerK;
    // End of variables declaration//GEN-END:variables
    private ParabolaPlot parabolaPlot = new ParabolaPlot();
}

class ParabolaPlot extends JXGraph.Plot {

    private double k;

    public void setK(double k) {
        double oldK = k;
        this.k = k;
        super.firePropertyChange("k", oldK, this.k);
    }

    @Override
    public double compute(double x) {
        return k * x * (1 - x);
    }
}

class LinePlot extends JXGraph.Plot {

    @Override
    public double compute(double x) {
        return x;
    }

}